project:
  name: cfn-test
  regions:
    - us-east-1  
  s3_bucket: group13-bucket-1
tests:
  default:
   template: main.yml
   parameters:
      VpcCIDR: 10.0.0.0/16
      PublicSubnetCIDR: 10.0.1.0/24
      PrivateSubnetCIDR: 10.0.2.0/24
      NatGatewaySubnetCidr: 10.0.1.0/24
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      KeyName: group13_key
