version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - pip install cfn-lint
      - pip install taskcat
  pre_build:
    commands:
      - cfn-lint main.yml
  build:
    commands:
      - taskcat test run

     
